### ISSUE TITLE
whooo we really need iOS for this, what a win

### ISSUE THREAD

**Issue by jlooper** [danielgek/nativescript-auto-fit-text#1]
would love to see iOS implemented!

**Comment by danielgek** [comment]
Hi @jlooper  this actually works for both platforms ;)

**Comment by jlooper** [comment]
oh, really? I couldn't make it work...I will try again!! It would be fabulous if it did!

**Comment by danielgek** [comment]
if you are still having problems pls tell me and I will take a look

**Comment by jlooper** [comment]
I see the issue...it does work well for iOS but not in my particular layout, which is cards. My fault, not yours...I'm sure there is a workaround via layouts so closing :) thanks!
